GET https://kasirajah.zeabur.app/categories

###
GET https://kasirajah.zeabur.app/categories/1

###
POST https://kasirajah.zeabur.app/categories
Content-Type: application/json

{
    "nama": "Alat Tulis",
    "description": "Perlengkapan alat tulis kantor"
}

###
GET https://kasirajah.zeabur.app/categories/5

###
PUT https://kasirajah.zeabur.app/categories/1
Content-Type: application/json

{
    "nama": "Elektronik Murah",
    "description": "Elektronik harga terjangkau"
}

###
DELETE https://kasirajah.zeabur.app/categories/1

###
GET https://kasirajah.zeabur.app/health
